version: "3.9"

services:
  memcached:
    image: memcached:1.6.12
    container_name: memcached
    ports:
      - "11211:11211"
  rabbitmq:
    image: rabbitmq:3.9.12-management-alpine
    container_name: rabbitmq
    env_file: .env
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}
