# Generated by Django 3.2.7 on 2021-10-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Dollar'), (2, 'Euro')], max_length=3),
        ),
    ]
