version: "3.9"

services:

  backend:
    container_name: backend
    image: local
    build: .
    stdin_open: true
    tty: true
    restart: always
    env_file: .env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - "./:/project/code"
    depends_on:
      - postgres
    ports:
      - "8000:8000"
      - "8001:8001"  # debug port

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}

volumes:
  db_data: {}
